### ISSUE TITLE
Outputs 0 line csv files

### ISSUE THREAD

**Issue by Ktar5** [cpancake/GameAnalytics-Processor#1]
Went through the process in the readme and it didn't give me anything except empty CSV files.

**Comment by dialupnoises** [comment]
I'm not sure how I missed this issue for so long, I'm sorry. If this is still a problem for you, could you provide a bit of data that this happens with so I can test it and see what's going on?

**Comment by Ktar5** [comment]
Honestly don't remember this at all haha, sorry.
